"""Single source of truth for the output CSV/XLSX column order."""

OUTPUT_COLUMNS = [
    "Instagram Username",
    "Profile Name",
    "Business Category",
    "Followers",
    "Following",
    "Posts Count",
    "Bio",
    "Website URL",
    "Email",
    "Phone Number",
    "WhatsApp Number",
    "Address",
    "Contact Button Available",
    "External Website",
    "Facebook Page",
    "Verified Account",
    "Profile Image URL",
    "Ecommerce Platform",
    "Meta Pixel Detected",
    "Google Analytics Detected",
    "Live Chat Widget",
    "Website Screenshot Path",
    "Last Scraped Date",
    "Profile URL",
    "Scrape Status",
    "Scrape Error",
]
